[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
tier_sol_miner = "K35hGi544FaiNx7s1MJuLuBxhr993Bq59CJR9mBaUna"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "https://api.devnet.solana.com"
wallet = ".anchor/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init_devnet = "ts-node scripts/init_devnet.ts"
init_mainnet = "ts-node scripts/init_mainnet.ts"
mint = "ts-node scripts/mint.ts"
add_tier = "ts-node scripts/add_tier.ts"
