[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tier_sol_miner = "K35hGi544FaiNx7s1MJuLuBxhr993Bq59CJR9mBaUna"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/teepy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
